version: 1
disable_existing_loggers: false

filters:
  stdout:
    (): app.tools.CustomFilter
    levels: [ DEBUG, INFO ]
  stderr:
    (): app.tools.CustomFilter
    levels: [ WARNING, ERROR, CRITICAL ]

formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s %(correlation_id)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  stdout:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
    filters: [ stdout ]
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: standard
    filters: [ stderr ]

loggers:
  app:
    level: INFO
    handlers: [ stdout, stderr ]
    propagate: no
  uvicorn:
    access:
      level: INFO
      propagate: no
      handlers: [ stdout ]
    error:
      level: WARNING
      propagate: no
      handlers: [ stderr ]
  sqlalchemy:
    engine:
      level: DEBUG
      propagate: no
      handlers: [ stdout, stderr ]
  weasyprint:
    level: ERROR
    handlers: [ stderr ]
    propagate: no
  fontTools:
    level: ERROR
    handlers: [ stderr ]
    propagate: no

root:
  level: INFO
  handlers: [ stdout, stderr ]
